<a class="success button expanded" href="#">Dodaj novu vrstu</a>

<table>
    <thead>
        <tr>
            <th>Znanstveni naziv</th>
            <th>Kategorija</th>
            <th>Istraživač</th>
            <th>Ugroženost</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        foreach($podaci as $red){
            include 'tablicaStavka.phtml';
        }
        ?>
    </tbody>
</table>
