<div class="grid-x grid-margin-x">
    <div class="large-12 cell">

<form class="log-in-form" method="POST"
action="/vrsta/dodajnovi">
 <label>Ime
    <input type="text" id="ime" name="ime" value="">
  </label>
  
  <label>Kategorija
    <input type="text" id="kategorija" name="kategorija" value="">
  </label>

  <label for="istrazivac">Odabrani istraživači</label>
            <select name="istrazivac" id="istrazivac">
                <option value="0">Odaberite istraživače</option>
                <?php foreach($istrazivaci as $istrazivac): ?>
                    <option <?php 
                        if($istrazivac->sifra==$vrsta->istrazivac){
                            echo 'selected="selected"';
                        }
                        
                        ?> value="<?php echo $istrazivac->sifra ?>">
                        <?php echo $istrazivac->ime . ' ' . $istrazivac->prezime ?>
                    </option>
                <?php endforeach;?>
            </select>

  <label>Ugroženost
    <input type="text" id="ugrozenost" name="ugrozenost" value="">
  </label>

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/vrsta/index" 
      class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" 
      value="Dodaj vrstu"></input>
    </div>
  </div>
</form>
</div>
</div>
<?php echo $poruka; ?>