<form class="log-in-form" method="POST"
action="/vrsta/dodajnovi">
 <label>Ime
    <input type="text" id="ime" name="ime" value="">
  </label>
  
  <label>Kategorija
    <input type="text" id="kategorija" name="kategorija" value="">
  </label>

  <label for="istrazivac">Istraživač</label>
      <select name="istrazivac" id="istrazivac">
          <option value="0">Odaberite istrazivača</option>
          <?php foreach($istrazivaci as $istrazivac): ?>
              <option <?php 
                   if($istrazivac->sifra==$projekt->istrazivac){
                       echo 'selected="selected"';
                  }
                  
                   ?> value="<?php echo $istrazivac->sifra ?>">
                  <?php echo $istrazivac->ime . ' ' . $istrazivac->prezime ?>
              </option>
          <?php endforeach;?>
      </select>

      <label for="ugrozenost">Ugroženost</label>
      <select name="ugrozenost" id="ugrozenost">
          <option value="0">Odaberite ugroženost</option>
          <?php foreach($ugrozenosti as $ugrozenost): ?>
              <option <?php 
                   if($ugrozenost->sifra==$projekt->ugrozenost){
                       echo 'selected="selected"';
                  }
                  
                   ?> value="<?php echo $ugrozenost->sifra ?>">
                  <?php echo $ugrozenost->šifra ?>
              </option>
          <?php endforeach;?>
      </select>




  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/vrsta/index" 
      class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" 
      value="Dodaj vrstu"></input>
    </div>
  </div>
</form>
<?php echo $poruka; ?>