<tr>
    <td title="naziv">
    <i class="fas fa-certificate" <?php 
    /*if(!$red->verificiran){
        echo 'style="color: gray" title="NIJE VERIFICIRAN"';
    }else{
        echo 'title="VERIFICIRAN"';
    }*/
    ?>></i>
    

    <span style="font-size: 1.4em;"><?php echo $red->ime?></span></td>
    <td style="text-align: right;" title="kategorija"><?php echo $red->kategorija?></td>
    <td style="text-align: right;" title="istrazivac"><?php echo $red->istrazivac?></td>
    <td style="text-align: right;" title="ugrozenost"><?php echo $red->ugrozenost?></td>
    <td>
        <a href="/vrsta/promjena?sifra=<?php echo $red->sifra?>"><i title="Promjeni" class="fas fa-edit fa-2x"></i></a> 
        <a href="/vrsta/obrisi?sifra=<?php echo $red->sifra?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </td>
</tr>