<a class="success button expanded" href="/projekt/novi">Dodaj novi projekt</a>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Istraživač</th>
            <th>Vrste</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        
        foreach($podaci as $red){
            include 'red.phtml';
        }
        ?>
    </tbody>
</table>
