<form class="log-in-form" method="POST"
action="/projekt/promjeni">
 <label>Naziv
    <input type="text" id="naziv" name="naziv" value="<?php 
    echo $projekt->naziv;
    ?>">
  </label>
  
  <label for="istrazivac">Istraživač</label>
      <select name="istrazivac" id="istrazivac">
          <option value="0">Odaberite istrazivača</option>
          <?php foreach($istrazivaci as $istrazivac): ?>
              <option <?php 
                   if($istrazivac->sifra==$projekt->istrazivac){
                       echo 'selected="selected"';
                  }
                  
                   ?> value="<?php echo $istrazivac->sifra ?>">
                  <?php echo $istrazivac->ime . ' ' . $istrazivac->prezime ?>
              </option>
          <?php endforeach;?>
      </select>

      <label for="vrsta">Vrsta</label>
      <select name="vrsta" id="vrsta">
          <option value="0">Odaberite vrstu</option>
          <?php foreach($vrste as $vrsta): ?>
              <option <?php 
                   if($vrsta->sifra==$projekt->vrsta){
                       echo 'selected="selected"';
                  }
                  
                   ?> value="<?php echo $vrsta->sifra ?>">
                  <?php echo $vrsta->šifra ?>
              </option>
          <?php endforeach;?>
      </select>

  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/projekt/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Promjeni projekt"></input>
    </div>
  </div>
  <input type="hidden" name="sifra" 
  value="<?php echo $projekt->sifra ?>">
</form>
<?php echo $poruka; ?>