<form class="log-in-form" method="POST"
action="/projekt/promjeni">
 <label>Naziv
    <input type="text" id="naziv" name="naziv" value="<?php 
    echo $projekt->naziv;
    ?>">
  </label>
  
  <label>Istraživač
            <select name="istrazivac" id="istrazivac">
                <option value="0">Odaberite istraživača</option>
                <?php foreach($istrazivaci as $istrazivac): ?>
                    <option value="<?php echo $istrazivac->sifra ?>">
                        <?php echo $istrazivac->ime . ' ' . $istrazivac->prezime ?>
                    </option>
                <?php endforeach;?>
            </select>
  </label>

  <label>Vrsta
            <select name="vrsta" id="vrsta">
                <option value="0">Odaberite vrstu</option>
                <?php foreach($vrste as $vrstavrsta): ?>
                    <option value="<?php echo $vrsta->sifra ?>">
                        <?php echo $vrsta->ime ?>
                    </option>
                <?php endforeach;?>
            </select>
  </label>


  <div class="grid-x grid-margin-x">
    <div class="large-6 cell">
      <a href="/projekt/index" class="alert button expanded">Odustani</a>
    </div>
    <div class="large-6 cell">
      <input type="submit" class="button expanded" value="Promjeni projekt"></input>
    </div>
  </div>
  <input type="hidden" name="sifra" 
  value="<?php echo $projekt->sifra ?>">
</form>
<?php echo $poruka; ?>